### ISSUE TITLE
开放平台如何处理公众号的事件、消息推送

### ISSUE THREAD

**Issue by qindj** [ArtisanCloud/PowerWechatTutorial#85]
Hi，

有个问题想咨询一下，微信官方文档：

https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/api/Before_Develop/Official_Accounts/Handling_of_news_and_events.html

想知道一下这个目前有没有实现？在文档上并没有看见

十分感谢！

**Comment by WalleV** [comment]
@qindj  https://powerwechat.artisan-cloud.com/zh/official-account/server.html
